//outputter.renderer.html,outputter.table
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import unit_threaded;

int main(string[] args)
{
  return args.runTests!(
                        "bud.indexer",
                        );
}
