name: Test and Build
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v0.4.0
        with:
          compiler: ${{ matrix.dc }}

      - uses: actions/cache@v1
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.sdl') }}
          restore-keys: |
            ${{ runner.os }}-dub-

      - name: Run tests
        run: dub test
                  
      - name: Build
        run: dub build
